import { Room, Lead, ChatMessage } from './types';

export const ROOMS: Room[] = [
  {
    id: 1,
    title: "Modern Studio Apartment",
    address: "Bandra West, Mumbai",
    rent: 18000,
    deposit: 36000,
    type: "Studio",
    furnished: true,
    ac: true,
    wifi: true,
    parking: false,
    bath: "Attached",
    water: "24/7",
    elec: "Included",
    rating: 4.7,
    reviews: 28,
    verified: true,
    instant: true,
    gender: "Any",
    occ: "Single",
    avail: "Immediate",
    imgs: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80"
    ],
    owner: {
      name: "Priya Sharma",
      avatar: "https://i.pravatar.cc/60?img=47",
      responseTime: "Usually within 1 hr",
      verified: true,
      rating: 4.8,
      listings: 3,
      upiId: "priya@upi"
    },
    safety: 88,
    amenities: ["WiFi", "AC", "Hot Water", "CCTV", "Power Backup", "Lift"],
    near: ["Bandra Station – 5 min", "Carter Road – 8 min", "Linking Road – 10 min"],
    extra: 500,
    moveIn: 54500,
    pets: false,
    food: false,
    laundry: true,
    kitchen: true,
    desc: "Beautifully designed studio in the heart of Bandra West. Modern interiors, great natural light, and all essential amenities included. Walking distance to cafes, restaurants, and Bandra Station.",
    ph: [16500, 17000, 17500, 17000, 17500, 18000],
    risk: "low",
    bg: true,
    city: "Mumbai",
    isSharingAvailable: true,
    totalOccupancy: 2,
    occupiedCount: 1,
    currentOccupant: {
      name: "Rahul K.",
      avatar: "https://i.pravatar.cc/60?img=11",
      occupation: "Software Engineer",
      age: 24,
      gender: "Male"
    }
  },
  {
    id: 2,
    title: "Spacious 1BHK Flat",
    address: "Koramangala, Bengaluru",
    rent: 22000,
    deposit: 44000,
    type: "1BHK",
    furnished: true,
    ac: true,
    wifi: true,
    parking: true,
    bath: "Attached",
    water: "24/7",
    elec: "Extra",
    rating: 4.5,
    reviews: 19,
    verified: true,
    instant: false,
    gender: "Any",
    occ: "Double",
    avail: "1 May",
    imgs: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80"
    ],
    owner: {
      name: "Arun Mehta",
      avatar: "https://i.pravatar.cc/60?img=32",
      responseTime: "Usually within 2 hrs",
      verified: true,
      rating: 4.6,
      listings: 5,
      upiId: "arun@upi"
    },
    safety: 82,
    amenities: ["WiFi", "AC", "Parking", "Hot Water", "Gym", "Pets OK"],
    near: ["Koramangala Forum – 7 min", "Indiranagar – 15 min", "Silk Board – 10 min"],
    extra: 0,
    moveIn: 66000,
    pets: true,
    food: false,
    laundry: true,
    kitchen: true,
    desc: "Bright and airy 1BHK in prime Koramangala location. Perfect for working professionals. Pet-friendly building with basement parking available.",
    ph: [20000, 21000, 20500, 21500, 22000, 22000],
    risk: "low",
    bg: false,
    city: "Bengaluru",
    isSharingAvailable: true,
    totalOccupancy: 2,
    occupiedCount: 1,
    currentOccupant: {
      name: "Suresh P.",
      avatar: "https://i.pravatar.cc/60?img=12",
      occupation: "Designer",
      age: 26,
      gender: "Male"
    }
  },
  {
    id: 3,
    title: "PG Room with Meals",
    address: "Hauz Khas, New Delhi",
    rent: 12000,
    deposit: 24000,
    type: "PG",
    furnished: true,
    ac: true,
    wifi: true,
    parking: false,
    bath: "Shared",
    water: "Morning/Evening",
    elec: "Included",
    rating: 4.3,
    reviews: 41,
    verified: true,
    instant: false,
    gender: "Female",
    occ: "Triple",
    avail: "Immediate",
    imgs: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80"
    ],
    owner: {
      name: "Sunita Kapoor",
      avatar: "https://i.pravatar.cc/60?img=25",
      responseTime: "Usually within 30 min",
      verified: true,
      rating: 4.7,
      listings: 2,
      upiId: "sunita@upi"
    },
    safety: 79,
    amenities: ["WiFi", "AC", "Hot Water", "CCTV", "Meals Included"],
    near: ["Hauz Khas Village – 3 min", "IIT Delhi – 10 min", "Green Park Metro – 8 min"],
    extra: 0,
    moveIn: 36000,
    pets: false,
    food: true,
    laundry: true,
    kitchen: false,
    desc: "Safe and homely PG accommodation in the vibrant Hauz Khas area. All meals included (breakfast & dinner). Female only, strict security.",
    ph: [10000, 11000, 11000, 12000, 12000, 12000],
    risk: "low",
    bg: false,
    city: "Delhi",
    isSharingAvailable: true,
    totalOccupancy: 3,
    occupiedCount: 2,
    currentOccupant: {
      name: "Ananya S.",
      avatar: "https://i.pravatar.cc/60?img=34",
      occupation: "Student",
      age: 21,
      gender: "Female"
    }
  },
  {
    id: 4,
    title: "Premium 2BHK Apartment",
    address: "Powai, Mumbai",
    rent: 35000,
    deposit: 70000,
    type: "2BHK",
    furnished: true,
    ac: true,
    wifi: true,
    parking: true,
    bath: "Attached",
    water: "24/7",
    elec: "Included",
    rating: 4.9,
    reviews: 56,
    verified: true,
    instant: true,
    gender: "Any",
    occ: "Family",
    avail: "Immediate",
    imgs: [
      "https://images.unsplash.com/photo-1560184897-ae8ead2e6ee5?w=600&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80"
    ],
    owner: {
      name: "Rajesh Nair",
      avatar: "https://i.pravatar.cc/60?img=12",
      responseTime: "Usually within 1 hr",
      verified: true,
      rating: 4.9,
      listings: 8,
      upiId: "rajesh@upi"
    },
    safety: 95,
    amenities: ["WiFi", "AC", "Parking", "Hot Water", "CCTV", "Power Backup", "Lift", "Gym", "Pets OK"],
    near: ["Hiranandani Gardens – 5 min", "Powai Lake – 8 min", "NITIE – 12 min"],
    extra: 1000,
    moveIn: 106000,
    pets: true,
    food: false,
    laundry: true,
    kitchen: true,
    desc: "Stunning premium 2BHK in Hiranandani Powai. Fully furnished with top-quality furniture, modular kitchen, and panoramic lake views. Perfect for families or co-living.",
    ph: [32000, 33000, 34000, 34000, 35000, 35000],
    risk: "low",
    bg: true,
    city: "Mumbai"
  },
  {
    id: 5,
    title: "Budget Single Room",
    address: "Andheri East, Mumbai",
    rent: 8500,
    deposit: 17000,
    type: "Single",
    furnished: false,
    ac: false,
    wifi: true,
    parking: false,
    bath: "Shared",
    water: "Morning Only",
    elec: "Extra",
    rating: 3.9,
    reviews: 12,
    verified: false,
    instant: false,
    gender: "Male",
    occ: "Single",
    avail: "15 May",
    imgs: [
      "https://images.unsplash.com/photo-1505873242700-f80d1e04be47?w=600&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&q=80"
    ],
    owner: {
      name: "Deepak Joshi",
      avatar: "https://i.pravatar.cc/60?img=53",
      responseTime: "Usually within 4 hrs",
      verified: false,
      rating: 3.8,
      listings: 1
    },
    safety: 62,
    amenities: ["WiFi", "CCTV"],
    near: ["Andheri Station – 10 min", "MIDC – 15 min", "Airport – 20 min"],
    extra: 200,
    moveIn: 25700,
    pets: false,
    food: false,
    laundry: false,
    kitchen: true,
    desc: "Affordable single room in Andheri East. Basic amenities, good connectivity. Ideal for budget-conscious professionals working in MIDC or near the airport.",
    ph: [8000, 8000, 8500, 8000, 8500, 8500],
    risk: "medium",
    bg: false,
    city: "Mumbai"
  },
  {
    id: 6,
    title: "1BHK Villa with Garden",
    address: "Whitefield, Bengaluru",
    rent: 16000,
    deposit: 32000,
    type: "1BHK",
    furnished: true,
    ac: false,
    wifi: true,
    parking: true,
    bath: "Attached",
    water: "24/7",
    elec: "Extra",
    rating: 4.6,
    reviews: 23,
    verified: true,
    instant: true,
    gender: "Any",
    occ: "Double",
    avail: "Immediate",
    imgs: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1574643156929-51e16f629679?w=600&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80"
    ],
    owner: {
      name: "Kavya Reddy",
      avatar: "https://i.pravatar.cc/60?img=41",
      responseTime: "Usually within 1 hr",
      verified: true,
      rating: 4.7,
      listings: 4
    },
    safety: 85,
    amenities: ["WiFi", "Parking", "Hot Water", "CCTV", "Power Backup", "Pets OK"],
    near: ["Whitefield Station – 8 min", "ITPL – 5 min", "Phoenix Marketcity – 12 min"],
    extra: 300,
    moveIn: 48300,
    pets: true,
    food: false,
    laundry: true,
    kitchen: true,
    desc: "Charming 1BHK villa with private garden in Whitefield. Ideal for nature lovers. Close to IT corridor. Peaceful neighbourhood with great connectivity.",
    ph: [14000, 15000, 15000, 16000, 16000, 16000],
    risk: "low",
    bg: false,
    city: "Bengaluru"
  },
  {
    id: 7,
    title: "Cozy Studio near Hinjewadi",
    address: "Phase 1, Hinjewadi, Pune",
    rent: 14500,
    deposit: 29000,
    type: "Studio",
    furnished: true,
    ac: true,
    wifi: true,
    parking: true,
    bath: "Attached",
    water: "24/7",
    elec: "Included",
    rating: 4.4,
    reviews: 15,
    verified: true,
    instant: true,
    gender: "Any",
    occ: "Single",
    avail: "Immediate",
    imgs: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80"
    ],
    owner: {
      name: "Manisha K.",
      avatar: "https://i.pravatar.cc/60?img=32",
      responseTime: "Within 2 hrs",
      verified: true,
      rating: 4.5,
      listings: 2,
      upiId: "manisha@upi"
    },
    safety: 82,
    amenities: ["WiFi", "AC", "Parking", "CCTV"],
    near: ["IT Park – 5 min", "Xion Mall – 10 min"],
    extra: 0,
    moveIn: 43500,
    pets: false,
    food: false,
    laundry: true,
    kitchen: true,
    desc: "Modern studio apartment in Hinjewadi Phase 1. Perfect for IT professionals. Fully furnished and ready to move in.",
    ph: [14000, 14500],
    risk: 'low',
    bg: true,
    city: "Pune"
  }
];

export const PIN_POS: Record<number, { x: number; y: number }> = {
  1: { x: 20, y: 30 },
  2: { x: 65, y: 55 },
  3: { x: 45, y: 20 },
  4: { x: 28, y: 65 },
  5: { x: 22, y: 48 },
  6: { x: 70, y: 72 }
};

export const AREA_ZONES = [
  { label: "Bandra West", x: 14, y: 22, color: "#dbeafe" },
  { label: "Koramangala", x: 58, y: 47, color: "#dcfce7" },
  { label: "Hauz Khas", x: 38, y: 12, color: "#fef3c7" },
  { label: "Powai", x: 22, y: 57, color: "#fce7f3" },
  { label: "Andheri", x: 16, y: 40, color: "#e0e7ff" },
  { label: "Whitefield", x: 62, y: 64, color: "#d1fae5" }
];

export const CHAT_MSGS: ChatMessage[] = [
  { id: 1, from: "owner", text: "Hello! Thanks for your interest in the Bandra studio 😊", time: "10:30 AM" },
  { id: 2, from: "user", text: "Hi Priya! I saw your listing. Is it still available?", time: "10:32 AM", status: "read" },
  { id: 3, from: "owner", text: "Yes, it's available from immediate! Would you like to schedule a visit?", time: "10:33 AM" },
  { id: 4, from: "user", text: "Great! Can I visit this Saturday around 11 AM?", time: "10:35 AM", status: "read" },
  { id: 5, from: "owner", text: "Saturday 11 AM works perfectly! I'll send you the exact address. 📍", time: "10:36 AM" }
];

export const OWNER_ROOMS = ROOMS.slice(0, 3);

export const ROOM_COORDS: Record<number, { lat: number; lng: number }> = {
  1: { lat: 19.0596, lng: 72.8295 }, // Bandra West
  2: { lat: 12.9352, lng: 77.6245 }, // Koramangala
  3: { lat: 28.5494, lng: 77.2044 }, // Hauz Khas
  4: { lat: 19.1176, lng: 72.9060 }, // Powai
  5: { lat: 19.1136, lng: 72.8697 }, // Andheri East
  6: { lat: 12.9698, lng: 77.7500 }, // Whitefield
  7: { lat: 18.5913, lng: 73.7389 }  // Hinjewadi, Pune
};

export const LEADS: Lead[] = [
  { id: "l1", name: "Amit Kumar", room: "Studio Bandra", time: "2 min ago", status: "New", img: 8 },
  { id: "l2", name: "Ritu Singh", room: "1BHK Koramangala", time: "1 hr ago", status: "Visit Set", img: 19 },
  { id: "l3", name: "Vikram Das", room: "Studio Bandra", time: "3 hrs ago", status: "Replied", img: 33 },
  { id: "l4", name: "Pooja Iyer", room: "2BHK Powai", time: "Yesterday", status: "New", img: 44 },
  { id: "l5", name: "Suresh B.", room: "Villa Whitefield", time: "2 days ago", status: "Replied", img: 55 }
];
